trigger:
  tags:
    include:
    - '*'

variables:
- group: Code signing
- name: "solution"
  value: "Clipple.sln"
- name: "buildPlatform"
  value: "x64"
- name: "buildConfiguration"
  value: "Release"
- name: "devCmd"
  value: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com'
- name: "disableToolPath" 
  value: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild'

pool:
  vmImage: 'windows-2022'
  
steps:

# The solution is set up so that a Release x64 build will not build the installer project, that will be done manually afterwards
- task: VSBuild@1
  displayName: "Restore and build Clipple.Wpf"
  inputs:
    solution: '$(solution)'
    msbuildArchitecture: 'x64'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:RuntimeIdentifier="win-$(buildPlatform)"
                  /t:Restore;Build'

# https://github.com/it3xl/MSBuild-DevEnv-Build-Server-Workarounds/issues/1#issuecomment-525435637
- task: BatchScript@1
  displayName: Enable .vdproj Builds
  inputs:
    filename: '"$(disableToolPath)\DisableOutOfProcBuild.exe"'
    workingFolder: '"$(disableToolPath)"'

- script: '"$(devCmd)" $(System.DefaultWorkingDirectory)\$(solution) /Build "Release" /Project $(System.DefaultWorkingDirectory)\Clipple.Setup\Clipple.Setup.vdproj'
  displayName: Build Installer

- task: Bash@3
  inputs:
    targetType: inline
    workingDirectory: $(PIPELINE.WORKSPACE)
    script: ls -R

# - task: NuGetCommand@2
#   inputs:
#     command: 'restore'
#     restoreSolution: 'Clipple.sln'
#     feedsToUse: 'select'
#   displayName: "Nuget"
  

  

# - task: GitHubRelease@1
#   inputs:
#     gitHubConnection: 'github'
#     repositoryName: '$(Build.Repository.Name)'
#     action: 'create'
#     target: '$(Build.SourceVersion)'
#     tagSource: 'gitTag'
#     assets: '$(Build.ArtifactStagingDirectory)\Packages\*\*.msix'
#     changeLogCompareToRelease: 'lastFullRelease'
#     changeLogType: 'commitBased'
#   displayName: "Release"