trigger:
  tags:
    include:
    - '*'

variables:
- group: Code signing
- name: "solution"
  value: "Clipple.sln"
- name: "buildPlatform"
  value: "x64"
- name: "buildConfiguration"
  value: "Release"
- name: "devCmd"
  value: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com'
- name: "disableToolPath" 
  value: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild'

pool:
  vmImage: 'windows-2022'
  
steps:

- task: DevEnvBuild@2
  inputs:
    solution: '$(solution)'
    buildCfg: '$(buildConfiguration)'
    buildPlatform: '$(buildPlatform)'
    vsVersion: 'latest'

- task: Bash@3
  inputs:
    targetType: inline
    workingDirectory: $(PIPELINE.WORKSPACE)
    script: ls -R

# - task: NuGetCommand@2
#   inputs:
#     command: 'restore'
#     restoreSolution: 'Clipple.sln'
#     feedsToUse: 'select'
#   displayName: "Nuget"
  

  

# - task: GitHubRelease@1
#   inputs:
#     gitHubConnection: 'github'
#     repositoryName: '$(Build.Repository.Name)'
#     action: 'create'
#     target: '$(Build.SourceVersion)'
#     tagSource: 'gitTag'
#     assets: '$(Build.ArtifactStagingDirectory)\Packages\*\*.msix'
#     changeLogCompareToRelease: 'lastFullRelease'
#     changeLogType: 'commitBased'
#   displayName: "Release"