trigger:
  tags:
    include:
    - '*'

variables:
- group: Code signing
- name: "solution"
  value: "Clipple.sln"
- name: "buildPlatform"
  value: "x64"
- name: "buildConfiguration"
  value: "Release"
- name: "packageDir"
  value: '$(Build.ArtifactStagingDirectory)\Packages'
  
pool:
  vmImage: 'windows-2022'

steps:
- powershell: |
   $versionTag = git describe --tags
   Write-Host "##vso[task.setvariable variable=versionTag]$versionTag"
  displayName: Get git version tag

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'Clipple.sln'
    feedsToUse: 'select'
  displayName: "Nuget"

- task: MSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArchitecture: 'x64'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArguments: '/p:RuntimeIdentifier="win-$(buildPlatform)"'
  displayName: 'Build'
  condition: 

- task: PowerShell@2
  inputs:
    filePath: 'squirrel.ps1'
    arguments: '$(versionTag)'

- task: Bash@3
  inputs:
    targetType: inline
    workingDirectory: $(PIPELINE.WORKSPACE)
    script: ls -R

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'seafraf'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    assets: |
      $(Build.SourcesDirectory)\Releases\*.nupkg
      $(Build.SourcesDirectory)\Releases\ClippleSetup.exe
      $(Build.SourcesDirectory)\Releases\RELEASES
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
  displayName: "Release"