# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

variables:
  buildPlatform: 'x64'
  buildConfiguration: 'Release'

pool:
  vmImage: 'windows-latest'

steps:

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'Clipple.sln'
    feedsToUse: 'select'

- task: MSBuild@1
  inputs:
    solution: 'Clipple.MSIX/Clipple.MSIX.wapproj'
    msbuildArchitecture: 'x64'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArguments: '/p:OutputPath=NonPackagedApp /p:UapAppxPackageBuildMode=SideLoadOnly /p:AppxBundle=Never /p:AppxPackageOutput=$(Build.ArtifactStagingDirectory)\Clipple.msix /p:AppxPackageSigningEnabled=false'
  displayName: 'Package'
  
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'codesign.pfx'
  displayName: 'Download cert'

- script: '"C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x86\signtool" sign /fd SHA256 /f $(Agent.TempDirectory)/codesign.pfx /p secret $(Build.ArtifactStagingDirectory)/Clipple.msix'
  displayName: 'Sign'