# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

variables:
- group: Code signing
- name: "solution"
  value: "Clipple.MSIX/Clipple.MSIX.wapproj"
- name: "buildPlatform"
  value: "x64"
- name: "buildConfiguration"
  value: "Release"
  
pool:
  vmImage: 'windows-2022'

steps:

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'Clipple.sln'
    feedsToUse: 'select'
  displayName: "Nuget"

- task: DownloadSecureFile@1
  name: signingCert
  inputs:
    secureFile: 'codesign.pfx'
  displayName: 'Cert DL'

- task: MSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArchitecture: 'x64'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArguments: '/p:AppxBundlePlatforms="$(buildPlatform)"  
                       /p:AppxPackageDir="$(appxPackageDir)"  
                       /p:AppxBundle=Never  
                       /p:UapAppxPackageBuildMode=SideLoadOnly  
                       /p:AppxPackageSigningEnabled=true 
                       /p:PackageCertificateThumbprint=""  
                       /p:PackageCertificateKeyFile="$(signingCert.secureFilePath)" 
                       /p:PackageCertificatePassword="$(codesignpw)"'
  displayName: 'Build'